server:
  port: 8083
---
spring.cloud.stream:
  function:
    definition: processor
  bindings:
    processor-in-0:
      destination: create-order
    processor-out-0:
      destination: order-update
---
service:
  endpoints:
    inventory: localhost:8081
    payment: localhost:8082