version: '3'
services:
  master:
    image: redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - master
    environment:
      - REDIS_HOSTS=master:master
    ports:
      - 8081:8081