version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=redis:redis
    ports:
      - 8081:8081
  producer:
    image: vinsdocker/redis-stream
    depends_on:
      - redis
    environment:
      - APP_ROLE=producer
      - SPRING_REDIS_HOST=redis
      - STREAM_KEY=purchase-events
      - PUBLISH_RATE=200
  consumer:
    image: vinsdocker/redis-stream
    depends_on:
      - redis
    environment:
      - APP_ROLE=consumer
      - SPRING_REDIS_HOST=redis
      - STREAM_KEY=purchase-events